### ISSUE TITLE
Accept numerical or text for Birth Month

### ISSUE THREAD

**Issue by rpocklington** [citizenlabsgr/voter-engagement#12]
Current behavior: It seems the birth month must be the name of the month spelled out. The name must even be in proper case.

Desired behavior: The birth month should accept both the month name (any case) or its ordinal number.

Example: "7", "July", and "july" should all be accepted as "July".

**Comment by jacebrowning** [comment]
Or maybe we could find a nice calendar picker and just extract the needed information from that?

**Comment by jacebrowning** [comment]
@rpocklington Check out the new behavior: https://vote.citizenlabs.org

I think we can still do better.

**Comment by diiq** [comment]
I think #30 wraps this up.
