### ISSUE TITLE
How should we handle erroneous region names from the SOS?

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/voter-engagement#23]
For example, many districts have the word "district" twice in their name:

<a href="https://cl.ly/3x0J3m202L1W" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/1l0Z2m0I182s33000Q3N/Screen%20Shot%202018-01-03%20at%2010.58.06%20AM.png" style="display: block;height: auto;width: 100%;"/></a>

Should we clean this up in our own data and consider "16th District" and "16th District District" to be the same region? Should we defer cleanup until presentation of the data? Something else?

**Comment by diiq** [comment]
Parse out the numbers and ditch the rest?

**Comment by jacebrowning** [comment]
That might simplify things.

@Allen616 Do you know if districts are always numbers?

**Comment by Allen616** [comment]
I believe so. What districts do we care about? I can imagine that in Lousianna they might have parish names. Do we care about that?

**Comment by jacebrowning** [comment]
We're received this kind of data so far from the MI SOS:

<a href="https://cl.ly/3r041u1g061V" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/0O1V1i0Q0C3c28452Y2n/Screen%20Shot%202018-03-07%20at%208.59.53%20PM.png" style="display: block;height: auto;width: 100%;"/></a>
