### ISSUE TITLE
Move or hide the footer on mobile

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/voter-engagement#37]
"View on GitHub" can overlap buttons and fields:
<a href="https://cl.ly/201T1a312f1Q" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/3F2D3x302y472v1w423i/Screen%20Shot%202018-02-28%20at%2011.31.14%20AM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by AaronJamesKing** [comment]
I have a fix ready for a pull request, but I just cloned the repo instead of forking. Can you give me access @jacebrowning ?

**Comment by jacebrowning** [comment]
@AaronJamesKing I just added you to our organization. Try it now!
