### ISSUE TITLE
Reloading '/registration-verified' prompts for email

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/voter-engagement#38]
# Steps

1. Go to https://vote.citizenlabs.org/login
2. Submit form with an existing voter's email
3. Click link in email to log in
4. Confirm you are taken to https://vote.citizenlabs.org/registration-verified
5. Reload the page

## Expected

Reloading the page has no effect on the page's content.

## Actual

An email form appears.

**Comment by diiq** [comment]
Not any more!
