### ISSUE TITLE
Month selection is not visible in Firefox

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/voter-engagement#45]
Can anyone else reproduce this?

<a href="https://cl.ly/270j1i2N1f3c" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/02132N262V1R0k1w0z28/Screen%20Shot%202018-04-04%20at%209.07.44%20AM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by diiq** [comment]
Reproduced. Looks like in firefox, options can be styled; so they're inheriting the white `color` but will need a `background-color` in order for the text to be readable.
