### ISSUE TITLE
Disable negative numbers on form birthday input.

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/voter-engagement#47]
<img width="627" alt="screen shot 2018-04-17 at 7 17 44 pm" src="https://user-images.githubusercontent.com/19940878/38903689-155b9bee-4274-11e8-9c08-d2aa52220929.png">

**Comment by AaronJamesKing** [comment]
Looks like this was fixed by e60359f, right?

**Comment by jacebrowning** [comment]
Yes, thanks for investigating!
